// <auto-generated />
using System;
using DynamicForm.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DynamicForm.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DynamicForm.Models.Form", b =>
                {
                    b.Property<int>("FormId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FormId"));

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("FormId");

                    b.ToTable("Forms");

                    b.HasData(
                        new
                        {
                            FormId = 1,
                            CreatedBy = "النظام",
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "نموذج لجمع البيانات الشخصية الأساسية",
                            IsActive = true,
                            Name = "نموذج البيانات الشخصية"
                        });
                });

            modelBuilder.Entity("DynamicForm.Models.FormField", b =>
                {
                    b.Property<int>("FieldId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FieldId"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FieldType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("FormId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Options")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ValidationRules")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("FieldId");

                    b.HasIndex("FormId");

                    b.ToTable("FormFields");

                    b.HasData(
                        new
                        {
                            FieldId = 1,
                            DisplayOrder = 1,
                            FieldName = "fullName",
                            FieldType = "text",
                            FormId = 1,
                            IsActive = true,
                            IsRequired = true,
                            Label = "الاسم الكامل"
                        },
                        new
                        {
                            FieldId = 2,
                            DisplayOrder = 2,
                            FieldName = "age",
                            FieldType = "text",
                            FormId = 1,
                            IsActive = true,
                            IsRequired = true,
                            Label = "العمر",
                            ValidationRules = "{\"min\":1,\"max\":120,\"type\":\"number\"}"
                        },
                        new
                        {
                            FieldId = 3,
                            DisplayOrder = 3,
                            FieldName = "birthDate",
                            FieldType = "date",
                            FormId = 1,
                            IsActive = true,
                            IsRequired = true,
                            Label = "تاريخ الميلاد"
                        },
                        new
                        {
                            FieldId = 4,
                            DisplayOrder = 4,
                            FieldName = "nationalId",
                            FieldType = "text",
                            FormId = 1,
                            IsActive = true,
                            IsRequired = true,
                            Label = "رقم الهوية الوطنية"
                        },
                        new
                        {
                            FieldId = 5,
                            DisplayOrder = 5,
                            FieldName = "nationalIdType",
                            FieldType = "dropdown",
                            FormId = 1,
                            IsActive = true,
                            IsRequired = true,
                            Label = "نوع الهوية",
                            Options = "[\"\\u0628\\u0637\\u0627\\u0642\\u0629 \\u0647\\u0648\\u064A\\u0629 \\u0648\\u0637\\u0646\\u064A\\u0629\",\"\\u062C\\u0648\\u0627\\u0632 \\u0633\\u0641\\u0631\",\"\\u0631\\u062E\\u0635\\u0629 \\u0642\\u064A\\u0627\\u062F\\u0629\",\"\\u0628\\u0637\\u0627\\u0642\\u0629 \\u0625\\u0642\\u0627\\u0645\\u0629\"]"
                        },
                        new
                        {
                            FieldId = 6,
                            DisplayOrder = 6,
                            FieldName = "phoneNumber",
                            FieldType = "text",
                            FormId = 1,
                            IsActive = true,
                            IsRequired = true,
                            Label = "رقم الهاتف",
                            ValidationRules = "{\"pattern\":\"^[0-9\\u002B\\\\-\\\\s]\\u002B$\"}"
                        },
                        new
                        {
                            FieldId = 7,
                            DisplayOrder = 7,
                            FieldName = "email",
                            FieldType = "email",
                            FormId = 1,
                            IsActive = true,
                            IsRequired = false,
                            Label = "البريد الإلكتروني"
                        },
                        new
                        {
                            FieldId = 8,
                            DisplayOrder = 8,
                            FieldName = "address",
                            FieldType = "text",
                            FormId = 1,
                            IsActive = true,
                            IsRequired = true,
                            Label = "العنوان"
                        },
                        new
                        {
                            FieldId = 9,
                            DisplayOrder = 9,
                            FieldName = "governorate",
                            FieldType = "dropdown",
                            FormId = 1,
                            IsActive = true,
                            IsRequired = true,
                            Label = "المنطقة/المحافظة",
                            Options = "[\"\\u0627\\u0644\\u0631\\u064A\\u0627\\u0636\",\"\\u0645\\u0643\\u0629 \\u0627\\u0644\\u0645\\u0643\\u0631\\u0645\\u0629\",\"\\u0627\\u0644\\u0645\\u062F\\u064A\\u0646\\u0629 \\u0627\\u0644\\u0645\\u0646\\u0648\\u0631\\u0629\",\"\\u0627\\u0644\\u0642\\u0635\\u064A\\u0645\",\"\\u0627\\u0644\\u0645\\u0646\\u0637\\u0642\\u0629 \\u0627\\u0644\\u0634\\u0631\\u0642\\u064A\\u0629\",\"\\u0639\\u0633\\u064A\\u0631\",\"\\u062A\\u0628\\u0648\\u0643\",\"\\u062D\\u0627\\u0626\\u0644\",\"\\u0627\\u0644\\u062D\\u062F\\u0648\\u062F \\u0627\\u0644\\u0634\\u0645\\u0627\\u0644\\u064A\\u0629\",\"\\u062C\\u0627\\u0632\\u0627\\u0646\",\"\\u0646\\u062C\\u0631\\u0627\\u0646\",\"\\u0627\\u0644\\u0628\\u0627\\u062D\\u0629\",\"\\u0627\\u0644\\u062C\\u0648\\u0641\"]"
                        },
                        new
                        {
                            FieldId = 10,
                            DisplayOrder = 10,
                            FieldName = "maritalStatus",
                            FieldType = "dropdown",
                            FormId = 1,
                            IsActive = true,
                            IsRequired = false,
                            Label = "الحالة الاجتماعية",
                            Options = "[\"\\u0623\\u0639\\u0632\\u0628\",\"\\u0645\\u062A\\u0632\\u0648\\u062C\",\"\\u0645\\u0637\\u0644\\u0642\",\"\\u0623\\u0631\\u0645\\u0644\"]"
                        });
                });

            modelBuilder.Entity("DynamicForm.Models.FormSubmission", b =>
                {
                    b.Property<int>("SubmissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubmissionId"));

                    b.Property<int>("FormId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SubmittedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("SubmittedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("SubmissionId");

                    b.HasIndex("FormId");

                    b.ToTable("FormSubmissions");
                });

            modelBuilder.Entity("DynamicForm.Models.FormSubmissionValue", b =>
                {
                    b.Property<int>("ValueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ValueId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("FieldId")
                        .HasColumnType("int");

                    b.Property<string>("FieldNameAtSubmission")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FieldTypeAtSubmission")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FieldValue")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("LabelAtSubmission")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("OptionsAtSubmission")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("SubmissionId")
                        .HasColumnType("int");

                    b.HasKey("ValueId");

                    b.HasIndex("FieldId");

                    b.HasIndex("SubmissionId");

                    b.ToTable("FormSubmissionValues");
                });

            modelBuilder.Entity("DynamicForm.Models.FormField", b =>
                {
                    b.HasOne("DynamicForm.Models.Form", "Form")
                        .WithMany("FormFields")
                        .HasForeignKey("FormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Form");
                });

            modelBuilder.Entity("DynamicForm.Models.FormSubmission", b =>
                {
                    b.HasOne("DynamicForm.Models.Form", "Form")
                        .WithMany("FormSubmissions")
                        .HasForeignKey("FormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Form");
                });

            modelBuilder.Entity("DynamicForm.Models.FormSubmissionValue", b =>
                {
                    b.HasOne("DynamicForm.Models.FormField", "FormField")
                        .WithMany("FormSubmissionValues")
                        .HasForeignKey("FieldId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DynamicForm.Models.FormSubmission", "FormSubmission")
                        .WithMany("FormSubmissionValues")
                        .HasForeignKey("SubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FormField");

                    b.Navigation("FormSubmission");
                });

            modelBuilder.Entity("DynamicForm.Models.Form", b =>
                {
                    b.Navigation("FormFields");

                    b.Navigation("FormSubmissions");
                });

            modelBuilder.Entity("DynamicForm.Models.FormField", b =>
                {
                    b.Navigation("FormSubmissionValues");
                });

            modelBuilder.Entity("DynamicForm.Models.FormSubmission", b =>
                {
                    b.Navigation("FormSubmissionValues");
                });
#pragma warning restore 612, 618
        }
    }
}
